### ISSUE TITLE
Coveralls triggers notifications before merging results from parallel CircleCI builds.

### ISSUE THREAD

**Issue by gogoLuby** [lemurheavy/coveralls-ruby#81]
Given 100% test coverage across 10 parallel CircleCI containers, we're seeing Coveralls trigger the coverage notification when the first of the parallel builds finishes, so we get notifications saying that we only have ~10% coverage. As the other builds finish, Coveralls correctly merges the results in its UI to reflect 100% coverage, but it doesn't issue new notifications.

Is there a way to make Coveralls wait until it has all the results from a given CI build? The ability to specify an expected number of inbound coverage reports would be best, but even enabling a time delay would be better. The existing '10% coverage' notifications this issue creates make Coveralls unusable for our engineering team. (related to https://github.com/lemurheavy/coveralls-public/issues/485)

**Comment by dankohn** [comment]
This circle.yml config is working for me:
```yml
post:
    - COVERALLS_PARALLEL=true bundle exec rake coveralls:push:
        parallel: true
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=[my token]
```
